# Generated by Django 5.1.3 on 2024-11-05 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
