# Generated by Django 5.1.3 on 2024-11-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_audiofile_uploaded_at_alter_audiofile_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio',
            new_name='audio_path',
        ),
    ]
