# Generated by Django 5.1.3 on 2024-11-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userfiles_delete_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='file_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
