# Generated by Django 5.1.3 on 2024-11-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userfiles_file_path_alter_userfiles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfiles',
            name='file_path',
        ),
    ]
