# Generated by Django 5.1.4 on 2024-12-11 14:23

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file_type',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
